"""Criação inicial das tabelas LogAcesso e SistemasOperacionais

Revision ID: 8532b740c828
Revises: 
Create Date: 2025-10-08 14:43:51.284118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8532b740c828'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistemas_operacionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_so', sa.String(length=100), nullable=False),
    sa.Column('versao_so', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_so', 'versao_so', name='_nome_versao_uc')
    )
    op.create_table('log_acessos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caminho_acessado', sa.String(length=500), nullable=False),
    sa.Column('ip_usuario', sa.String(length=50), nullable=True),
    sa.Column('data_acesso', sa.DateTime(), nullable=True),
    sa.Column('so_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['so_id'], ['sistemas_operacionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_acessos')
    op.drop_table('sistemas_operacionais')
    # ### end Alembic commands ###
